import React, { useMemo, useState, useRef } from 'react';
import { X, Download, Share2, Printer, ChevronLeft, ChevronRight, Activity, Calendar, ShieldCheck, Target, TrendingUp, AlertTriangle, ZoomIn, ZoomOut, Maximize, Search, Menu, Check, List, Image as ImageIcon } from 'lucide-react';
import { Report, useData } from '../../context/DataContext';
import { TrendingDown } from 'lucide-react';
import { formatNumber } from '../../lib/dataUtils';
import { useCurrency } from '../../hooks/useCurrency';
import { ShareModal } from './ShareModal';
import { ExportProgressModal } from './ExportProgressModal';

export function ReportViewer({ report, onClose }: { report: Report | null, onClose: () => void }) {
  const { datasets } = useData();
  const { formatCurrency } = useCurrency();
  const [zoom, setZoom] = useState(1);
  const [isShareOpen, setIsShareOpen] = useState(false);
  const [isExporting, setIsExporting] = useState(false);
  const [exportStage, setExportStage] = useState('');
  const [exportProgress, setExportProgress] = useState(0);
  const [showSidebar, setShowSidebar] = useState(false);
  const [currentPage, setCurrentPage] = useState(1);
  
  const dataset = useMemo(() => {
    if (!report) return null;
    return datasets.find(d => d.name === report.datasetName);
  }, [report, datasets]);

  const metrics = report?.metricsSnapshot || dataset?.metrics;

  if (!report) return null;

  const handlePrint = () => {
    window.print();
  };

  const handleExport = async () => {
    const payload = {
      reportType: report.type,
      dataset: report.datasetName,
      generatedDate: report.date,
      metrics: metrics
    };
    const dataStr = "data:text/json;charset=utf-8," + encodeURIComponent(JSON.stringify(payload, null, 2));
    const link = document.createElement("a");
    link.setAttribute("href", dataStr);
    link.setAttribute("download", `${report.type.replace(/\s+/g, '_')}_${report.datasetName.replace(/\s+/g, '_')}.json`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  return (
    <div className="fixed inset-0 z-50 flex flex-col bg-[var(--color-brand-bg)] animate-in slide-in-from-bottom-4 duration-300 print:bg-white print:block">
      <ShareModal report={report} isOpen={isShareOpen} onClose={() => setIsShareOpen(false)} />
      <ExportProgressModal isOpen={isExporting} stage={exportStage} progress={exportProgress} />

      {/* Header */}
      <div className="h-16 border-b border-[var(--color-brand-border)] px-6 flex items-center justify-between shrink-0 bg-[var(--color-brand-card)] print:hidden">
        <div className="flex items-center gap-4">
          <button onClick={onClose} className="p-2 -ml-2 rounded-lg text-[var(--color-brand-muted)] hover:text-[var(--color-brand-text)] hover:bg-[var(--color-brand-bg)] transition-colors">
            <X className="w-5 h-5" />
          </button>
          <div className="h-6 w-px bg-[var(--color-brand-border)]"></div>
          <div>
            <h2 className="text-[var(--color-brand-text)] font-semibold flex items-center gap-2">
              {report.name} 
              
            </h2>
            <p className="text-xs text-[var(--color-brand-muted)]">Generated by {report.generatedBy} on {new Date(report.date).toLocaleString()}</p>
          </div>
        </div>
        
        {/* Toolbar */}
        <div className="flex items-center gap-1.5 mr-4 bg-[var(--color-brand-bg)] border border-[var(--color-brand-border)] rounded-lg p-1 hidden lg:flex">
          <button 
            onClick={() => setShowSidebar(s => !s)}
            className={`p-1.5 rounded transition-colors ${showSidebar ? 'text-[var(--color-brand-text)] bg-[var(--color-brand-card)] border border-[var(--color-brand-border)]' : 'text-[var(--color-brand-muted)] hover:text-[var(--color-brand-text)] hover:bg-[var(--color-brand-card)]'}`}
            title="Sidebar/Outline"
          >
            <Menu className="w-4 h-4" />
          </button>
          <div className="w-px h-4 bg-[var(--color-brand-border)] mx-1"></div>
          <button className="p-1.5 text-[var(--color-brand-muted)] hover:text-[var(--color-brand-text)] hover:bg-[var(--color-brand-card)] rounded transition-colors" title="Search">
            <Search className="w-4 h-4" />
          </button>
          <div className="w-px h-4 bg-[var(--color-brand-border)] mx-1"></div>
          <button onClick={() => setZoom(z => Math.max(0.5, z - 0.1))} className="p-1.5 text-[var(--color-brand-muted)] hover:text-[var(--color-brand-text)] hover:bg-[var(--color-brand-card)] rounded transition-colors" title="Zoom Out">
            <ZoomOut className="w-4 h-4" />
          </button>
          <span className="text-xs font-medium text-[var(--color-brand-text)] min-w-[3rem] text-center">{Math.round(zoom * 100)}%</span>
          <button onClick={() => setZoom(z => Math.min(2, z + 0.1))} className="p-1.5 text-[var(--color-brand-muted)] hover:text-[var(--color-brand-text)] hover:bg-[var(--color-brand-card)] rounded transition-colors" title="Zoom In">
            <ZoomIn className="w-4 h-4" />
          </button>
          <div className="w-px h-4 bg-[var(--color-brand-border)] mx-1"></div>
          <button onClick={() => setZoom(1)} className="p-1.5 text-[var(--color-brand-muted)] hover:text-[var(--color-brand-text)] hover:bg-[var(--color-brand-card)] rounded transition-colors" title="Fit Width">
            <Maximize className="w-4 h-4" />
          </button>
        </div>

        <div className="flex items-center gap-2">
          <button onClick={handlePrint} className="px-3 py-1.5 bg-[var(--color-brand-bg)] border border-[var(--color-brand-border)] rounded-lg text-xs font-medium text-[var(--color-brand-text)] hover:text-[var(--color-brand-primary)] transition-colors flex items-center gap-2">
            <Printer className="w-3.5 h-3.5" /> Print
          </button>
          <button onClick={() => setIsShareOpen(true)} className="px-3 py-1.5 bg-[var(--color-brand-bg)] border border-[var(--color-brand-border)] rounded-lg text-xs font-medium text-[var(--color-brand-text)] hover:text-[var(--color-brand-primary)] transition-colors flex items-center gap-2">
            <Share2 className="w-3.5 h-3.5" /> Share
          </button>
          <button 
            onClick={handleExport}
            disabled={isExporting}
            className="px-4 py-1.5 bg-[var(--color-brand-primary)] text-[var(--color-brand-bg)] border border-transparent rounded-lg text-xs font-bold hover:bg-[var(--color-brand-secondary)] transition-colors shadow-sm flex items-center gap-2 disabled:opacity-70 disabled:cursor-wait"
          >
            {isExporting ? <span className="animate-spin rounded-full h-3.5 w-3.5 border-2 border-[var(--color-brand-bg)] border-t-transparent"></span> : <Download className="w-3.5 h-3.5" />}
            {isExporting ? 'Exporting...' : 'Export PDF'}
          </button>
        </div>
      </div>

      <div className="flex-1 flex overflow-hidden">
        {/* Sidebar */}
        {showSidebar && (
          <div className="w-64 border-r border-[var(--color-brand-border)] bg-[var(--color-brand-card)] flex flex-col shrink-0 animate-in slide-in-from-left-4 duration-300 print:hidden">
            <div className="p-4 border-b border-[var(--color-brand-border)] flex items-center justify-between">
              <span className="text-sm font-semibold text-[var(--color-brand-text)]">Pages</span>
            </div>
            <div className="flex-1 overflow-y-auto p-4 space-y-4">
              {[1].map((_, i) => (
                <div 
                  key={i}
                  onClick={() => setCurrentPage(i + 1)}
                  className={`cursor-pointer rounded-lg border-2 p-1 transition-colors ${currentPage === i + 1 ? 'border-[var(--color-brand-primary)]' : 'border-transparent hover:border-[var(--color-brand-border)]'}`}
                >
                  <div className="aspect-[1/1.4] bg-white rounded flex items-center justify-center shadow-sm relative overflow-hidden">
                    <div className="absolute top-2 left-2 right-2 h-2 bg-gray-200 rounded"></div>
                    <div className="absolute top-5 left-2 right-2 h-1 bg-gray-100 rounded"></div>
                    <div className="absolute top-7 left-2 right-2 h-1 bg-gray-100 rounded"></div>
                    <span className="text-gray-400 font-bold text-xl">{i + 1}</span>
                  </div>
                  <div className="text-center mt-2 text-xs text-[var(--color-brand-muted)] font-medium">Page {i + 1}</div>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Report Body / Canvas */}
        <div className="flex-1 overflow-auto p-8 bg-[var(--color-brand-bg)] print:p-0 print:overflow-visible">
          <div 
            className="max-w-[850px] mx-auto bg-white min-h-[1100px] shadow-2xl rounded-sm p-12 text-gray-900 relative transition-transform origin-top print:!transform-none print:!m-0 print:shadow-none print:w-full print:max-w-none print:border-0"
            style={{ transform: `scale(${zoom})`, marginBottom: `${Math.max(0, (zoom - 1) * 1100)}px` }}
          >
            
            <div className="border-b-2 border-gray-900 pb-8 mb-8 flex justify-between items-end">
               <div>
                 <h1 className="text-4xl font-black tracking-tight text-gray-900 mb-2">{report.type}</h1>
                 <p className="text-lg text-gray-600">Dataset: {report.datasetName}</p>
               </div>
               <div className="text-right">
                 <p className="text-sm font-bold text-gray-900">{new Date(report.date).toLocaleDateString()}</p>
                 <p className="text-xs text-gray-500">CONFIDENTIAL</p>
               </div>
            </div>

            {currentPage === 1 ? (
              <>
                <div className="mb-12">
                  <h2 className="text-lg font-bold uppercase tracking-wider text-gray-900 mb-4 flex items-center gap-2">
                    <Activity className="w-5 h-5 text-blue-600" /> Executive Summary
                  </h2>
                  <p className="text-gray-700 leading-relaxed mb-4">
                    This report provides a comprehensive analysis of the <span className="font-bold">{report.datasetName}</span> dataset. 
                    Based on the {metrics?.datasetStats?.totalRows ? formatNumber(metrics.datasetStats.totalRows) : 'analyzed'} records processed, this document outlines performance, distribution, and structural data quality.
                  </p>
                  {metrics?.recommendations && metrics.recommendations.length > 0 && (
                    <div className="mt-4">
                      <p className="text-gray-900 font-bold mb-2">Key Recommendations:</p>
                      <ul className="list-disc pl-5 text-gray-700 space-y-2">
                        {metrics.recommendations.slice(0, 3).map((rec: any, idx: number) => (
                          <li key={idx}>
                            <span className="font-semibold">{rec.title}:</span> {rec.desc}
                          </li>
                        ))}
                      </ul>
                    </div>
                  )}
                </div>

                <div className="grid grid-cols-2 gap-8 mb-12">
                   <div className="bg-gray-50 p-6 rounded-lg border border-gray-200">
                     <h3 className="text-xs font-bold uppercase tracking-wider text-gray-500 mb-2">Total Revenue</h3>
                     <p className="text-3xl font-black text-gray-900">
                        {metrics?.totalRevenue ? formatCurrency(metrics.totalRevenue) : 'N/A'}
                     </p>
                     {metrics?.revenueChange !== null && metrics?.revenueChange !== undefined && (
                       <p className={`text-sm font-bold mt-1 flex items-center gap-1 ${metrics.revenueChange >= 0 ? 'text-green-600' : 'text-red-600'}`}>
                         {metrics.revenueChange >= 0 ? <TrendingUp className="w-3.5 h-3.5" /> : <TrendingDown className="w-3.5 h-3.5" />} 
                         {metrics.revenueChange > 0 ? '+' : ''}{metrics.revenueChange}% vs previous period
                       </p>
                     )}
                   </div>
                   <div className="bg-gray-50 p-6 rounded-lg border border-gray-200">
                     <h3 className="text-xs font-bold uppercase tracking-wider text-gray-500 mb-2">Total Volume</h3>
                     <p className="text-3xl font-black text-gray-900">
                        {metrics?.datasetStats?.totalRows ? formatNumber(metrics.datasetStats.totalRows) : 'N/A'}
                     </p>
                     <p className="text-sm text-gray-600 font-bold mt-1 flex items-center gap-1">
                       <Target className="w-3.5 h-3.5" /> Core metric
                     </p>
                   </div>
                </div>

                <div className="mb-12">
                  <h2 className="text-lg font-bold uppercase tracking-wider text-gray-900 mb-4 flex items-center gap-2">
                    <ShieldCheck className="w-5 h-5 text-blue-600" /> Key Dataset Insights
                  </h2>
                  <ul className="space-y-4 text-gray-700 list-disc pl-5">
                    {metrics?.categoryData && metrics.categoryData.length > 0 && (
                      <li><span className="font-bold text-gray-900">Category Dominance:</span> The leading category is <span className="font-semibold text-blue-700">{metrics.categoryData[0].name}</span>, driving a significant portion of overall metrics.</li>
                    )}
                    {metrics?.aov !== undefined && (
                      <li><span className="font-bold text-gray-900">Average Transaction:</span> Typical order value sits at <span className="font-semibold text-blue-700">{formatCurrency(metrics.aov)}</span> across the dataset.</li>
                    )}
                    {metrics?.totalCustomers && (
                      <li><span className="font-bold text-gray-900">Customer Base:</span> Analysis identified <span className="font-semibold text-blue-700">{formatNumber(metrics.totalCustomers)}</span> distinct customers contributing to the period's performance.</li>
                    )}
                    {!metrics && (
                      <li><AlertTriangle className="w-4 h-4 inline mr-1 text-yellow-500" /> Detailed insights require a richer dataset with recognizable revenue or categorical columns.</li>
                    )}
                  </ul>
                </div>
              </>
            ) : (
              <div className="flex flex-col items-center justify-center h-[500px] text-gray-400">
                <p className="mb-2 uppercase tracking-wider text-sm font-semibold">Page {currentPage}</p>
                <p>Additional charts and metrics visualization section.</p>
              </div>
            )}

            <div className="absolute bottom-12 left-12 right-12 border-t border-gray-300 pt-6 flex justify-between items-center text-xs text-gray-400 print:static print:mt-12 print:border-t-2 print:border-gray-900">
              <p>InsightIQ Enterprise Analytics</p>
              <p>Page {currentPage}</p>
            </div>
            
          </div>
        </div>
      </div>
      
      {/* Footer Tooling */}
      <div className="h-10 bg-[var(--color-brand-card)] border-t border-[var(--color-brand-border)] shrink-0 flex items-center justify-between px-6 text-xs text-[var(--color-brand-muted)] print:hidden z-10 relative">
        <div className="flex items-center gap-4">
          <span>1 Page</span>
          <div className="w-px h-3 bg-[var(--color-brand-border)]"></div>
          <span>Dataset: {report.datasetName}</span>
        </div>
        <div className="flex items-center gap-2">
          <span>Page {currentPage}</span>
          <div className="flex items-center gap-1 ml-2">
            <button 
              onClick={() => setCurrentPage(p => Math.max(1, p - 1))}
              disabled={currentPage === 1}
              className="p-1 hover:text-[var(--color-brand-text)] rounded hover:bg-[var(--color-brand-bg)] transition-colors disabled:opacity-50"
            >
              <ChevronLeft className="w-4 h-4" />
            </button>
            <button 
              onClick={() => setCurrentPage(1)}
              disabled={true}
              className="p-1 hover:text-[var(--color-brand-text)] rounded hover:bg-[var(--color-brand-bg)] transition-colors disabled:opacity-50"
            >
              <ChevronRight className="w-4 h-4" />
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
